Updated and documented PowerShell scripts
lucabol/University pull request #5
Opened 2017-06-15 12:40 UTC by CamillaCauterucci

2017-06-16 08:58 UTC, lucabol requested changes
Good job guys. The code looks good. Take a look at the comments. I'll send comments on the doc and videos separately.

2017-06-16 08:58 UTC, lucabol commented on Src/Add-AzureDtlVM.ps1
> +    This script adds the specified number of Azure virtual machines in the specified DevTest Lab.
Remove repetition 'specified' in all rest of document.

2017-06-16 08:58 UTC, lucabol commented on Src/Add-AzureDtlVM.ps1
> +    It allows the creation of the VMs inside a specific lab. This script needs to be scheduled for the creation of the VMs of each lab.
Change 'This script needs to be ...' to 'This script can be run either from command line or Azure Automation' in all the rest of source files.

2017-06-16 08:58 UTC, lucabol commented on Src/Add-AzureDtlVM.ps1
> +    This script adds the specified number of Azure virtual machines in the specified DevTest Lab.
Sorry, I meant 'in all the rest of the source files whenever you use this phrase'

2017-06-16 08:58 UTC, lucabol commented on Src/Add-AzureDtlVM.ps1
> +    It allows the creation of the VMs inside a specific lab. This script needs to be scheduled for the creation of the VMs of each lab.
Please expand on the description. I.E. 'It allows to specify most parameters of interest for a lab creation (i.e. image name, network name, etc...). It should be a paragraph with one to three phrases. Please do this for all the other descriptions of functions in the source files.

2017-06-16 08:58 UTC, lucabol commented on Src/Add-AzureDtlVM.ps1
> +    Optional. Path to the Deployment Template File.
Or URL of the template file when running from Azure Automation.

2017-06-16 08:58 UTC, lucabol commented on Src/Add-AzureDtlVM.ps1
> +    Optional. Path to the Shutdown file.
Same as above.

2017-06-16 08:58 UTC, lucabol commented on Src/Add-AzureDtlVM.ps1
> +.EXAMPLE
Add an example of running from Azure Automation. Look at the automation variables and pass those as parameters.

2017-06-16 08:58 UTC, lucabol commented on Src/Add-AzureDtlVM.ps1
> -    RemoveBatchVms -vms $failed -batchSize $removeBatchSize -profilePath $profilePath -credentialsKind $credentialsKind
Why removing profilePath? It seems that it should be used in the File branch inside the RemoveBatchVms function. It should be passed into Remove-AzureDtlLabVMs as a parameter.

2017-06-16 08:58 UTC, lucabol commented on Src/Add-AzureDtlVMAutoVar.ps1
> +    This script adds the specified number of Azure virtual machines in the specified DevTest Lab.
'by reading some variable from ...' to keep it to one phrase.

2017-06-16 08:58 UTC, lucabol commented on Src/Add-AzureDtlVM.ps1
> +    Mandatory. Desired total number of VMs in the lab.
Add what this is used for, i.e. if the lab already contains N machines, it won't create more.

2017-06-16 08:58 UTC, lucabol commented on Src/Add-AzureDtlVMAutoVar.ps1
> +    Mandatory. Desired total number of VMs in the lab.
Change as above.

2017-06-16 08:58 UTC, lucabol commented on Src/DeallocateStoppedVM.ps1
> +    This script deallocates every Azure virtual machines which are stopped.
deallocates every stopped Azure ...

2017-06-16 08:58 UTC, lucabol commented on Src/DeallocateStoppedVM.ps1
> +    This script deallocates every Azure virtual machines which are stopped in the specified DevTest Lab.
Expand comment. Read code and look at definition of Stopped (i.e. stopped but not deallocated).

2017-06-16 08:58 UTC, lucabol commented on Src/DeallocateStoppedVM.ps1
> +    Mandatory. The name of the Dev Test Lab to clean up.
No clean up here.

2017-06-16 08:58 UTC, lucabol commented on Src/Manage-AzureDtlFixedPool.ps1
> +    This script verifies whether the Virtual Machine pool of the Lab equals to the PoolSize specified as Azure Tag of Lab.
No, this script doesn't verify, but guarantees as stated in the DESCRIPTION.

2017-06-16 08:58 UTC, lucabol commented on Src/Manage-AzureDtlFixedPool.ps1
> +    # Hack for runbook
Wow. Good catch :-)

2017-06-16 08:58 UTC, lucabol commented on Src/Remove-AzureDtlLabVMs.ps1
> +.PARAMETER ids
doc profilePath param

2017-06-16 08:58 UTC, lucabol commented on Src/Remove-AzureDtlLabVMs.ps1
> +    This script deletes every Azure virtual machines in the specified DevTest Lab.
No, it deletes the ones with the passed Ids.

2017-06-16 08:58 UTC, lucabol commented on Src/Remove-AzureDtlLabVMs.ps1
> +            DeleteSingleVM -id $id -profilePath $profilePath
Why doesn't call RemoveBatchVMs to do it in parallel?

2017-06-16 08:58 UTC, lucabol commented on Src/Remove-AzureDtlLabVMs.ps1
> +            DeleteSingleVM -id $id -profilePath $profilePath
Oh wait, forget about that. I get it. this is called by RemoveBatchVMs  ...

2017-06-16 08:58 UTC, lucabol commented on Src/Remove-GroupPermissionsDevTestLab.ps1
> +    This script removes the specified role to the AD Group in the specified DevTest Lab.
Confusing. Removes the specific AD group from the role?

2017-06-16 08:58 UTC, lucabol commented on Src/Shutdown scripts/LoadIdleScript.ps1
> +        Optional. The name of the container
Name of SAS token.

2017-06-16 08:58 UTC, lucabol commented on Src/Shutdown scripts/ShutdownOnIdleV2.ps1
> +        This script checks VM Status
No, it shutdowns the machine if the user hasn't been active.

2017-06-16 08:58 UTC, lucabol commented on Src/Test-AzureDtlVMs.ps1
> +    Mandatory. The name of the Dev Test Lab to clean up.
No cleaning up.

2017-06-16 08:58 UTC, lucabol commented on TODO.txt
> -1. Doc for class scenario (step by step installation)
Remove this file.

2017-06-16 08:58 UTC, lucabol commented on Src/SimplifiedJSPortal/Readme.md
> +## Placeholder replacement
Please describe what goes into this fields.

2017-06-16 10:46 UTC, CamillaCauterucci commented on Src/Add-AzureDtlVM.ps1
> +    This script adds the specified number of Azure virtual machines in the specified DevTest Lab.
Done

2017-06-16 10:47 UTC, CamillaCauterucci commented on Src/Add-AzureDtlVM.ps1
> +    Mandatory. Desired total number of VMs in the lab.
Done

2017-06-16 10:47 UTC, CamillaCauterucci commented on Src/Add-AzureDtlVM.ps1
> +    Optional. Path to the Deployment Template File.
Done

2017-06-16 10:47 UTC, CamillaCauterucci commented on Src/Add-AzureDtlVM.ps1
> +    Optional. Path to the Shutdown file.
Done

2017-06-16 10:47 UTC, CamillaCauterucci commented on Src/Add-AzureDtlVMAutoVar.ps1
> +    This script adds the specified number of Azure virtual machines in the specified DevTest Lab.
Done

2017-06-16 10:48 UTC, CamillaCauterucci commented on Src/DeallocateStoppedVM.ps1
> +    This script deallocates every Azure virtual machines which are stopped.
Done

2017-06-16 10:48 UTC, CamillaCauterucci commented on Src/DeallocateStoppedVM.ps1
> +    This script deallocates every Azure virtual machines which are stopped in the specified DevTest Lab.
Done

2017-06-16 10:48 UTC, CamillaCauterucci commented on Src/DeallocateStoppedVM.ps1
> +    Mandatory. The name of the Dev Test Lab to clean up.
Modified.

2017-06-16 10:48 UTC, CamillaCauterucci commented on Src/Manage-AzureDtlFixedPool.ps1
> +    This script verifies whether the Virtual Machine pool of the Lab equals to the PoolSize specified as Azure Tag of Lab.
Modified

2017-06-16 10:49 UTC, CamillaCauterucci commented on Src/Remove-AzureDtlLabVMs.ps1
> +    This script deletes every Azure virtual machines in the specified DevTest Lab.
Modified

2017-06-16 10:49 UTC, CamillaCauterucci commented on Src/Remove-AzureDtlLabVMs.ps1
> +.PARAMETER ids
Done

2017-06-16 10:49 UTC, CamillaCauterucci commented on Src/Shutdown scripts/LoadIdleScript.ps1
> +        Optional. The name of the container
Modified

2017-06-16 10:49 UTC, CamillaCauterucci commented on TODO.txt
> -1. Doc for class scenario (step by step installation)
Removed

2017-06-16 11:49 UTC, lucabol commented on Src/Add-AzureDtlVM.ps1
> +    This script adds the specified number of Azure virtual machines in the specified DevTest Lab.
I don't see these changed in your check-in. Just see current pharasing.

2017-06-16 11:51 UTC, CamillaCauterucci commented on Src/Add-AzureDtlVM.ps1
> +    This script adds the specified number of Azure virtual machines in the specified DevTest Lab.
Just did it.

2017-06-16 11:58 UTC, lucabol commented on Src/Remove-AzureDtlLabVMs.ps1
> +.PARAMETER ids
Verified.

2017-06-16 11:59 UTC, lucabol commented on TODO.txt
> -1. Doc for class scenario (step by step installation)
Verified.

2017-06-16 12:08 UTC, lucabol commented on Src/Add-AzureDtlVM.ps1
> +    RemoveBatchVms -vms $failed -batchSize $removeBatchSize -credentialsKind $credentialsKind -profilePath $profilePath
Have you tested that it still works after passing the parameter in? Who removed in the first place and why?

2017-06-16 12:08 UTC, lucabol commented on Src/Common.ps1
> +    param($vms, $BatchSize, $credentialsKind, $profilePath)
But then profilePath is not used i the function (i.e. it is not passed to Remove-AzureDtlLabVMs. If we reintroduce this parameter, we have to understand why it was removed, if it is ok to put it back and test it at least once.

2017-06-16 12:08 UTC, lucabol commented on Src/Remove-AzureDtlLabVMs.ps1
> +            DeleteSingleVM -id $id -profilePath $profilePath
Verified.

2017-06-16 12:09 UTC, lucabol commented on Src/Shutdown scripts/ShutdownOnIdleV2.ps1
> +        This script checks VM Status
Verified.

2017-06-16 12:10 UTC, lucabol commented on Src/Test-AzureDtlVMs.ps1
> +    Mandatory. The name of the Dev Test Lab to clean up.
Verified.

2017-06-16 12:12 UTC, lucabol commented on Src/Add-AzureDtlVM.ps1
> +    This script adds the number of Azure virtual machines in the DevTest Lab.
This scripts adds the specified number of Azure virtual machines to a DevTest Lab.

2017-06-16 12:14 UTC, lucabol commented on Src/Add-GroupPermissionsDevTestLab.ps1
> +    This script adds the role to the AD Group in the DevTest Lab.
This script adds the specified role to the AD Group in the DevTest Lab.

2017-06-16 12:14 UTC, lucabol commented on Src/Add-AzureDtlVM.ps1
> +    It allows the creation of the VMs inside a specific lab. This script needs to be scheduled for the creation of the VMs of each lab.
Verified.

2017-06-16 12:14 UTC, lucabol commented on Src/Add-AzureDtlVM.ps1
> +    Mandatory. Desired total number of VMs in the lab.
Verified.

2017-06-16 12:14 UTC, lucabol commented on Src/Add-AzureDtlVM.ps1
> +    Optional. Path to the Deployment Template File.
Verified.

2017-06-16 12:15 UTC, lucabol commented on Src/Add-AzureDtlVM.ps1
> +    Optional. Path to the Shutdown file.
Verified.

2017-06-16 12:15 UTC, lucabol commented on Src/Add-AzureDtlVMAutoVar.ps1
> +    This script adds the specified number of Azure virtual machines in the specified DevTest Lab.
Verified.

2017-06-16 12:15 UTC, lucabol commented on Src/Add-AzureDtlVMAutoVar.ps1
> +    Mandatory. Desired total number of VMs in the lab.
Verified.

2017-06-16 12:16 UTC, lucabol commented on Src/DeallocateStoppedVM.ps1
> +    This script deallocates every Azure virtual machines which are stopped.
Verified.

2017-06-16 12:16 UTC, lucabol commented on Src/DeallocateStoppedVM.ps1
> +    This script deallocates every Azure virtual machines which are stopped in the specified DevTest Lab.
Verified.

2017-06-16 12:16 UTC, lucabol commented on Src/DeallocateStoppedVM.ps1
> +    Mandatory. The name of the Dev Test Lab to clean up.
Verified.

2017-06-16 12:16 UTC, lucabol commented on Src/Manage-AzureDtlFixedPool.ps1
> +    This script verifies whether the Virtual Machine pool of the Lab equals to the PoolSize specified as Azure Tag of Lab.
Verified.

2017-06-16 12:17 UTC, lucabol commented on Src/Manage-AzureDtlFixedPool.ps1
> +    # Hack for runbook
Verified.

2017-06-16 12:17 UTC, lucabol commented on Src/Remove-AzureDtlLabVMs.ps1
> +    This script deletes every Azure virtual machines in the specified DevTest Lab.
Verified.

2017-06-16 12:18 UTC, lucabol commented on Src/Remove-GroupPermissionsDevTestLab.ps1
> +    This script removes the specified role to the AD Group in the specified DevTest Lab.
Verified.

2017-06-16 12:18 UTC, lucabol commented on Src/Shutdown scripts/LoadIdleScript.ps1
> +        Optional. The name of the container
Verified.

2017-06-16 12:29 UTC, CamillaCauterucci commented on Src/SimplifiedJSPortal/Readme.md
> +## Placeholder replacement
Done

2017-06-16 12:42 UTC, lucabol commented on Src/SimplifiedJSPortal/Readme.md
> +## Placeholder replacement
Verified.

2017-06-16 12:54 UTC, CamillaCauterucci commented on Src/Add-AzureDtlVM.ps1
> +.EXAMPLE
Done

2017-06-16 13:03 UTC, lucabol commented on Src/Add-AzureDtlVM.ps1
> +.EXAMPLE
This wouldn't work in Azure Automation as it reference files. It should reference URLs. That's the main difference.

2017-06-16 13:06 UTC, lucabol commented on Src/Readme.md
> +# Source folder
We need just one Readme.md at the University level (one level up), that describes everything in the repo. Usually there are no Readme.md in the Src folders. Also, please use MarkDown for formatting. If you look at this link the functions don't come out nicely formatted: https://github.com/lucabol/University/tree/FixesToCheck/Src

2017-06-17 06:20 UTC, lucabol commented on Readme.md
> +# University repository
Two changes for this Readme please:
1. Under each category of scripts, put the list of scripts and what each one does
2. For each item (video, doc or script) put a link that brings you directly to it

2017-06-17 07:02 UTC, lucabol commented on Src/Add-AzureDtlVM.ps1
> +    This script adds the specified number of Azure virtual machines in the specified DevTest Lab.
Verified.

2017-06-17 07:02 UTC, lucabol commented on Src/Add-AzureDtlVM.ps1
> +.EXAMPLE
Verified

2017-06-19 07:50 UTC, CamillaCauterucci commented on Readme.md
> +# University repository
Done

2017-06-19 10:14 UTC, lucabol approved these changes

2017-06-19 10:16 UTC, merged